// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RemesaSmartSV.Data;

#nullable disable

namespace RemesaSmartSV.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RemesaSmartSV.Entities.AporteMeta", b =>
                {
                    b.Property<int>("IdAporte")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdAporte"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdMeta")
                        .HasColumnType("integer");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("IdAporte");

                    b.HasIndex("IdMeta");

                    b.ToTable("Aportes");
                });

            modelBuilder.Entity("RemesaSmartSV.Entities.Categoria", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCategoria"));

                    b.Property<string>("Icono")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("IdHogar")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("IdCategoria");

                    b.HasIndex("IdHogar");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("RemesaSmartSV.Entities.EducacionFinanciera", b =>
                {
                    b.Property<int>("IdTip")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTip"));

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("IdTip");

                    b.HasIndex("IdCategoria");

                    b.ToTable("TipsFinancieros");
                });

            modelBuilder.Entity("RemesaSmartSV.Entities.Hogar", b =>
                {
                    b.Property<int>("IdHogar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdHogar"));

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NombreFamiliar")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("IdHogar");

                    b.ToTable("Hogares");
                });

            modelBuilder.Entity("RemesaSmartSV.Entities.MetaAhorro", b =>
                {
                    b.Property<int>("IdMeta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMeta"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("FechaLimite")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdHogar")
                        .HasColumnType("integer");

                    b.Property<decimal>("MontoActual")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("MontoObjetivo")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("IdMeta");

                    b.HasIndex("IdHogar");

                    b.ToTable("MetasAhorro");
                });

            modelBuilder.Entity("RemesaSmartSV.Entities.Movimiento", b =>
                {
                    b.Property<int>("IdMovimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMovimiento"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("integer");

                    b.Property<int>("IdHogar")
                        .HasColumnType("integer");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("OrigenEmisora")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("IdMovimiento");

                    b.HasIndex("IdCategoria");

                    b.HasIndex("IdHogar");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Movimientos");
                });

            modelBuilder.Entity("RemesaSmartSV.Entities.Presupuesto", b =>
                {
                    b.Property<int>("IdPresupuesto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPresupuesto"));

                    b.Property<int>("IdCategoria")
                        .HasColumnType("integer");

                    b.Property<int>("IdHogar")
                        .HasColumnType("integer");

                    b.Property<DateTime>("MesAnio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("MontoLimite")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("IdPresupuesto");

                    b.HasIndex("IdCategoria");

                    b.HasIndex("IdHogar");

                    b.ToTable("Presupuestos");
                });

            modelBuilder.Entity("RemesaSmartSV.Entities.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("ContrasenaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdHogar")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("IdUsuario");

                    b.HasIndex("IdHogar");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("RemesaSmartSV.Entities.AporteMeta", b =>
                {
                    b.HasOne("RemesaSmartSV.Entities.MetaAhorro", "MetaAhorro")
                        .WithMany("Aportes")
                        .HasForeignKey("IdMeta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MetaAhorro");
                });

            modelBuilder.Entity("RemesaSmartSV.Entities.Categoria", b =>
                {
                    b.HasOne("RemesaSmartSV.Entities.Hogar", "Hogar")
                        .WithMany("Categorias")
                        .HasForeignKey("IdHogar")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hogar");
                });

            modelBuilder.Entity("RemesaSmartSV.Entities.EducacionFinanciera", b =>
                {
                    b.HasOne("RemesaSmartSV.Entities.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("RemesaSmartSV.Entities.MetaAhorro", b =>
                {
                    b.HasOne("RemesaSmartSV.Entities.Hogar", "Hogar")
                        .WithMany("MetasAhorro")
                        .HasForeignKey("IdHogar")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hogar");
                });

            modelBuilder.Entity("RemesaSmartSV.Entities.Movimiento", b =>
                {
                    b.HasOne("RemesaSmartSV.Entities.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RemesaSmartSV.Entities.Hogar", "Hogar")
                        .WithMany()
                        .HasForeignKey("IdHogar")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RemesaSmartSV.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Hogar");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("RemesaSmartSV.Entities.Presupuesto", b =>
                {
                    b.HasOne("RemesaSmartSV.Entities.Categoria", "Categoria")
                        .WithMany("Presupuestos")
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RemesaSmartSV.Entities.Hogar", "Hogar")
                        .WithMany("Presupuestos")
                        .HasForeignKey("IdHogar")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Hogar");
                });

            modelBuilder.Entity("RemesaSmartSV.Entities.Usuario", b =>
                {
                    b.HasOne("RemesaSmartSV.Entities.Hogar", "Hogar")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdHogar")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hogar");
                });

            modelBuilder.Entity("RemesaSmartSV.Entities.Categoria", b =>
                {
                    b.Navigation("Presupuestos");
                });

            modelBuilder.Entity("RemesaSmartSV.Entities.Hogar", b =>
                {
                    b.Navigation("Categorias");

                    b.Navigation("MetasAhorro");

                    b.Navigation("Presupuestos");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("RemesaSmartSV.Entities.MetaAhorro", b =>
                {
                    b.Navigation("Aportes");
                });
#pragma warning restore 612, 618
        }
    }
}
