name: CI Backend RemesaSmart

on:
    push:
        branches: [ main, develop ]
    pull_request:
        branches: [ main, develop ]

jobs:
    build-and-test:
        runs-on: ubuntu-latest

        steps:
            - name: Check out repository
              uses: actions/checkout@v4

            - name: Set up .NET 8
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: '8.0.x'

            - name: Restore dependencies
              run: dotnet restore

            - name: Build project
              run: dotnet build --no-restore --configuration Release

            - name: Restore test dependencies
              run: dotnet restore RemesaSmartSV.Tests/RemesaSmartSV.Tests.csproj

            - name: Run xUnit tests
              run: dotnet test RemesaSmartSV.Tests/RemesaSmartSV.Tests.csproj --no-restore --configuration Release --verbosity normal
              